baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
image = "/images/flower.png"

[permalinks]
  posts = "/posts/:slug/"
  contact = "/contact/"
  projects = "/projects/"

[params]
  dateFormat = "Jan 6, 2006"

[taxonomies]
  author = "authors"
  catergory = "categories"
