baseURL = 'https://mxso.netlify.app'
languageCode = 'en-us'
title = 'MSN'

[permalinks]
  posts = "/posts/:slug/"
  contact = "/contact/"
  projects = "/projects/"

[params]
  image = "/images/profile/main-img.webp"
  dateFormat = "Jan 6, 2006"
  skills = ["java", "spring", "javascript", "python","sql", "golang", "c", "IoT"] 
  description = "Masonwabe Shaun Nkombisa's Personal Site"

[taxonomies]
  author = "authors"
  catergory = "categories"

[pagination]
  pagerSize = 4
